include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    - camel_case_types
    - constant_identifier_names
    - empty_statements
    - annotate_overrides
    - directives_ordering
    - curly_braces_in_flow_control_structures
    - non_constant_identifier_names
    - prefer_single_quotes
    - unnecessary_this
    - unnecessary_new
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_const
    - always_declare_return_types
    - avoid_print
    - always_put_control_body_on_new_line
    - unnecessary_final
    - camel_case_extensions
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_empty_else
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - no_duplicate_case_values
    - package_api_docs
    - package_names
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unrelated_type_equality_checks








